on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

name: Generate Pull Request Next Stats

jobs:
  stats:
    name: PR Stats
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@38c59cfe9af77dc06f9235182017a6ae416a9223
        id: check
        with:
          reaction: eyes
          trigger: 'TypeOfWebBot stats'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - if: steps.check.outputs.triggered == 'true'
        uses: xt0rted/pull-request-comment-branch@v1.2.0
        id: comment-branch
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}

      - if: steps.check.outputs.triggered == 'true'
        uses: typeofweb/next-stats-action@master
        env:
          PR_STATS_COMMENT_TOKEN: ${{secrets.PR_STATS_COMMENT_TOKEN}}
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          BRANCH: ${{steps.comment-branch.outputs.head_ref}} # prRef
